### PR TITLE
Open solutions instead of discussion page.

### PR DESCRIPTION
**Pull request by jhshi**
Discussion pages are obsolete. Open solutions page instead. The URL pattern is
`<BASE_URL>/problems/<name>/#/solutions`.

### CODE REVIEW

**Comment by chishui** [comment]
The new discussion url is like this: https://discuss.leetcode.com/category/9/two-sum.
I think we should update the discussion url and add a new hotkey to solution.

**Comment by jhshi** [comment]
Agreed. But how to find out the category number of a problem?

**Comment by chishui** [comment]
I'll try to find a way.

**Comment by jhshi** [comment]
Meanwhile, should I go ahead and add the shortcut for solutions? What's a good shortcut? I'm thinking "o" given that "s" is already assigned to "submit". Or a capital "S"?

**Comment by chishui** [comment]
Sure, I'd prefer "S" as a shortcut.

**Comment by jhshi** [comment]
FYI, I left the "discussion" url alone so that you can work on it. This PR only contains the new "S" shortcut for solutions page.

**Pull request merged**
