### PR TITLE
Print debug information for failed testcase.

### PR DESCRIPTION
**Pull request by jhshi**

### CODE REVIEW

**Comment by chishui** [comment]
What's the new look of the submit result message? My last commit has a test case fail, working on it.

**Comment by jhshi** [comment]
On failed testcase, the toast message is like this:

image

**Comment by chishui** [comment]
The test case input or output or stdout data sometimes will be so big that the toast is not able to hold. If it can, I think we need a better format or even a better container to display the whole information rather than just simply put them into the toast.

**Comment by jhshi** [comment]
Just consolidated some old commits.

I agree. Sometimes those text can be large. What format do you suggest?

**Comment by chishui** [comment]
I suggest a well structured urwid view, each section has a fixed size and for oversized contends user can scroll to view the whole content. The view could be a overlay view or we can just append the result view to the bottom of the detail view just like leetcode webpage does.

**Comment by jhshi** [comment]
As a newbie to urwid, this is as far as I can get. The right way is probably to use Pile to stack the detail and result view, but I can not figure out how to assign the height of the detail view.

image

**Comment by jhshi** [comment]
Somehow the test is failing. and `upstream/master` is failing on my environment as well. Is there a requirements.txt file that helps testing and debuging? Also, does Python version matter? I tried both 2.7.6 (ubuntu 14.04 default) and 2.7.13 (latest), both setup has test fails.

**Comment by chishui** [comment]
Sorry for delay, I was out for a meeting this whole week. Test depends on two mock library, mock and requests-mock, both for python 2.7. I haven't tried 2.7.6 but my python version is 2.7.13. Please use pip to install these two packages. You could run test by command 'make test', you could refer to Makefile for information of the command.

**Comment by jhshi** [comment]
Closing since it seems you have a better solution.

**Pull request closed without merging**
